-- Add the new columns (safe if already present) and load Offseason Rankings 1.
alter table public.weeks add column if not exists label text;
alter table public.weeks add column if not exists hero_image_url text;

insert into public.weeks (season, week_number, display_date, tagline, label, status, published_at, worst_name, worst_take, dropped_out, archive_note) values
  (2026, 1, 'Feb 2026', 'your favorite rapper''s favorite top 10 list', 'Offseason Rankings 1', 'published', now(), 'Drake Maye', 'I know he''s top 10. He''s also the worst. Super Bowl was SO bad.', '[{"name":"Jalen Hurts","previousRank":10}]'::jsonb, 'The offseason list opens with Lamar. Obviously.')
on conflict (season, week_number) do update set display_date = excluded.display_date, label = excluded.label, status = excluded.status, published_at = excluded.published_at, worst_name = excluded.worst_name, worst_take = excluded.worst_take, dropped_out = excluded.dropped_out, archive_note = excluded.archive_note;

delete from public.rankings where week_id = (select id from public.weeks where season = 2026 and week_number = 1);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 1, 'lamar-jackson', 'Lamar Jackson', 'BAL', 'Anyone that doesn’t have Lamar number one is telling on themselves.', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 2, 'josh-allen', 'Josh Allen', 'BUF', 'We love the cannon arm. We love the running ability. That one fumble before half against Denver though. Yikes.', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 3, 'matthew-stafford', 'Matthew Stafford', 'LAR', 'Decent chance he falls off a cliff next year and I regret this rating.', '{"kind":"up","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 4, 'patrick-mahomes', 'Patrick Mahomes', 'KC', 'He''s hurt and felt like he was sneaky not good last year. But he''s Mahomes.', '{"kind":"down","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 5, 'trevor-lawrence', 'Trevor Lawrence', 'JAX', 'Including the Clemson years, feels like I’ve spent almost a decade calling him a bust. I''m not apologizing, but I am putting him at 5.', '{"kind":"up","delta":2}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 6, 'dak-prescott', 'Dak Prescott', 'DAL', 'Cowboys were awful last year, Dak was awesome. If you think he''s the problem in Dallas, I can''t help you.', '{"kind":"up","delta":2}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 7, 'joe-burrow', 'Joe Burrow', 'CIN', 'Most overrated player in the league, but I guess he''s top 7.', '{"kind":"up","delta":2}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 8, 'brock-purdy', 'Brock Purdy', 'SF', 'The Purdy thing is real. Sorry if you don''t see it yet.', '{"kind":"new"}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 9, 'justin-herbert', 'Justin Herbert', 'LAC', 'The Justin Herbert leap has to come eventually. Right? Right???', '{"kind":"down","delta":3}'::jsonb);
insert into public.rankings (week_id, rank, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2026 and week_number = 1), 10, 'drake-maye', 'Drake Maye', 'NE', 'Heart says I never want him in the top 10 again. Head says 10 is fair.', '{"kind":"down","delta":5}'::jsonb);

