-- Auto-generated by scripts/gen-seed-sql.ts — do not edit by hand.
-- Run AFTER schema.sql + rls.sql. Safe to re-run (idempotent).

-- Teams
insert into public.teams (code, name, primary_color) values
  ('BAL', 'Baltimore Ravens', '#241773'),
  ('KC', 'Kansas City Chiefs', '#E31837'),
  ('BUF', 'Buffalo Bills', '#C60C30'),
  ('CIN', 'Cincinnati Bengals', '#FB4F14'),
  ('PHI', 'Philadelphia Eagles', '#004C54'),
  ('HOU', 'Houston Texans', '#03202F'),
  ('WAS', 'Washington Commanders', '#5A1414'),
  ('SF', 'San Francisco 49ers', '#AA0000'),
  ('DAL', 'Dallas Cowboys', '#003594'),
  ('SEA', 'Seattle Seahawks', '#002244'),
  ('CAR', 'Carolina Panthers', '#0085CA'),
  ('MIA', 'Miami Dolphins', '#008E97'),
  ('LAC', 'Los Angeles Chargers', '#0080C6'),
  ('MIN', 'Minnesota Vikings', '#4F2683'),
  ('GB', 'Green Bay Packers', '#203731'),
  ('DET', 'Detroit Lions', '#0076B6'),
  ('TB', 'Tampa Bay Buccaneers', '#D50A0A'),
  ('ATL', 'Atlanta Falcons', '#A71930'),
  ('NO', 'New Orleans Saints', '#D3BC8D'),
  ('ARI', 'Arizona Cardinals', '#97233F'),
  ('LAR', 'Los Angeles Rams', '#003594'),
  ('CHI', 'Chicago Bears', '#0B162A'),
  ('NYJ', 'New York Jets', '#125740'),
  ('NYG', 'New York Giants', '#0B2265'),
  ('PIT', 'Pittsburgh Steelers', '#FFB612'),
  ('DEN', 'Denver Broncos', '#FB4F14'),
  ('JAX', 'Jacksonville Jaguars', '#006778'),
  ('TEN', 'Tennessee Titans', '#4B92DB'),
  ('IND', 'Indianapolis Colts', '#002C5F'),
  ('NE', 'New England Patriots', '#002244'),
  ('CLE', 'Cleveland Browns', '#311D00'),
  ('LV', 'Las Vegas Raiders', '#A5ACAF')
on conflict (code) do update set name = excluded.name, primary_color = excluded.primary_color;

-- Quarterbacks
insert into public.qbs (slug, full_name, espn_id, default_team_code) values
  ('aaron-rodgers', 'Aaron Rodgers', 8439, 'PIT'),
  ('adrian-martinez', 'Adrian Martinez', 4361182, 'SF'),
  ('aidan-oconnell', 'Aidan O''Connell', 4260394, 'LV'),
  ('andy-dalton', 'Andy Dalton', 14012, 'PHI'),
  ('anthony-richardson-sr', 'Anthony Richardson Sr.', 4429084, 'IND'),
  ('athan-kaliakmanis', 'Athan Kaliakmanis', 4432722, 'WAS'),
  ('bailey-zappe', 'Bailey Zappe', 4250360, 'NYJ'),
  ('baker-mayfield', 'Baker Mayfield', 3052587, 'TB'),
  ('behren-morton', 'Behren Morton', 4431465, 'NE'),
  ('bo-nix', 'Bo Nix', 4426338, 'DEN'),
  ('brady-cook', 'Brady Cook', 4429435, 'NYJ'),
  ('brandon-allen', 'Brandon Allen', 2574511, 'NYG'),
  ('brock-purdy', 'Brock Purdy', 4361741, 'SF'),
  ('bryce-young', 'Bryce Young', 4685720, 'CAR'),
  ('cj-stroud', 'C.J. Stroud', 4432577, 'HOU'),
  ('cade-klubnik', 'Cade Klubnik', 4685413, 'NYJ'),
  ('caleb-williams', 'Caleb Williams', 4431611, 'CHI'),
  ('cam-miller', 'Cam Miller', 4693331, 'MIA'),
  ('cam-ward', 'Cam Ward', 4688380, 'TEN'),
  ('carson-beck', 'Carson Beck', 4430841, 'ARI'),
  ('carson-wentz', 'Carson Wentz', 2573079, 'MIN'),
  ('carter-bradley', 'Carter Bradley', 4362260, 'JAX'),
  ('case-keenum', 'Case Keenum', 15168, 'CHI'),
  ('chris-oladokun', 'Chris Oladokun', 4044111, 'KC'),
  ('cole-payton', 'Cole Payton', 4879250, 'PHI'),
  ('connor-bazelak', 'Connor Bazelak', 4426444, 'TB'),
  ('dak-prescott', 'Dak Prescott', 2577417, 'DAL'),
  ('daniel-jones', 'Daniel Jones', 3917792, 'IND'),
  ('davis-mills', 'Davis Mills', 4242546, 'HOU'),
  ('deshaun-watson', 'Deshaun Watson', 3122840, 'CLE'),
  ('diego-pavia', 'Diego Pavia', 5084180, 'BAL'),
  ('dillon-gabriel', 'Dillon Gabriel', 4427238, 'CLE'),
  ('dj-uiagalelei', 'DJ Uiagalelei', 4429020, 'LAC'),
  ('drake-maye', 'Drake Maye', 4431452, 'NE'),
  ('drew-allar', 'Drew Allar', 4714771, 'PIT'),
  ('drew-lock', 'Drew Lock', 3924327, 'SEA'),
  ('easton-stick', 'Easton Stick', 3120590, 'IND'),
  ('fernando-mendoza', 'Fernando Mendoza', 4837248, 'LV'),
  ('gardner-minshew-ii', 'Gardner Minshew II', 4038524, 'ARI'),
  ('garrett-nussmeier', 'Garrett Nussmeier', 4567747, 'KC'),
  ('geno-smith', 'Geno Smith', 15864, 'NYJ'),
  ('graham-mertz', 'Graham Mertz', 4426335, 'HOU'),
  ('haynes-king', 'Haynes King', 4428993, 'CAR'),
  ('hendon-hooker', 'Hendon Hooker', 4240858, 'TEN'),
  ('hunter-dekkers', 'Hunter Dekkers', 4565358, 'NO'),
  ('jj-mccarthy', 'J.J. McCarthy', 4433970, 'MIN'),
  ('jack-strand', 'Jack Strand', 5344782, 'ATL'),
  ('jacob-clark', 'Jacob Clark', 4569535, 'LV'),
  ('jacoby-brissett', 'Jacoby Brissett', 2578570, 'ARI'),
  ('jake-browning', 'Jake Browning', 3886812, 'TB'),
  ('jalen-hurts', 'Jalen Hurts', 4040715, 'PHI'),
  ('jalen-milroe', 'Jalen Milroe', 4432734, 'SEA'),
  ('jalon-daniels', 'Jalon Daniels', 4596472, 'TB'),
  ('jameis-winston', 'Jameis Winston', 2969939, 'NYG'),
  ('jared-goff', 'Jared Goff', 3046779, 'DET'),
  ('jarrett-stidham', 'Jarrett Stidham', 3892775, 'DEN'),
  ('jaxson-dart', 'Jaxson Dart', 4689114, 'NYG'),
  ('jayden-daniels', 'Jayden Daniels', 4426348, 'WAS'),
  ('joe-burrow', 'Joe Burrow', 3915511, 'CIN'),
  ('joe-fagnano', 'Joe Fagnano', 4429582, 'BAL'),
  ('joe-flacco', 'Joe Flacco', 11252, 'CIN'),
  ('joe-milton-iii', 'Joe Milton III', 4360698, 'DAL'),
  ('joey-aguilar', 'Joey Aguilar', 5151948, 'JAX'),
  ('jordan-love', 'Jordan Love', 4036378, 'GB'),
  ('josh-allen', 'Josh Allen', 3918298, 'BUF'),
  ('josh-johnson', 'Josh Johnson', 11394, 'CIN'),
  ('justin-fields', 'Justin Fields', 4362887, 'KC'),
  ('justin-herbert', 'Justin Herbert', 4038941, 'LAC'),
  ('kedon-slovis', 'Kedon Slovis', 4428512, 'ARI'),
  ('kenny-pickett', 'Kenny Pickett', 4240703, 'CAR'),
  ('kirk-cousins', 'Kirk Cousins', 14880, 'LV'),
  ('kurtis-rourke', 'Kurtis Rourke', 4430431, 'SF'),
  ('kyle-allen', 'Kyle Allen', 3115293, 'BUF'),
  ('kyle-mccord', 'Kyle McCord', 4433971, 'GB'),
  ('kyler-murray', 'Kyler Murray', 3917315, 'MIN'),
  ('kyron-drones', 'Kyron Drones', 4678010, 'GB'),
  ('lamar-jackson', 'Lamar Jackson', 3916387, 'BAL'),
  ('luke-altmyer', 'Luke Altmyer', 4597679, 'DET'),
  ('mac-jones', 'Mac Jones', 4241464, 'SF'),
  ('malik-willis', 'Malik Willis', 4242512, 'MIA'),
  ('marcus-mariota', 'Marcus Mariota', 2576980, 'WAS'),
  ('mark-gronowski', 'Mark Gronowski', 4695400, 'MIA'),
  ('mason-rudolph', 'Mason Rudolph', 3116407, 'PIT'),
  ('matthew-caldwell', 'Matthew Caldwell', 4877717, 'LAR'),
  ('matthew-stafford', 'Matthew Stafford', 12483, 'LAR'),
  ('max-brosmer', 'Max Brosmer', 4573398, 'MIN'),
  ('michael-penix-jr', 'Michael Penix Jr.', 4360423, 'ATL'),
  ('miller-moss', 'Miller Moss', 4431580, 'CHI'),
  ('mitchell-trubisky', 'Mitchell Trubisky', 3039707, 'TEN'),
  ('nick-mullens', 'Nick Mullens', 3059989, 'JAX'),
  ('patrick-mahomes', 'Patrick Mahomes', 3139477, 'KC'),
  ('quinn-ewers', 'Quinn Ewers', 4889929, 'MIA'),
  ('riley-leonard', 'Riley Leonard', 4683423, 'IND'),
  ('sam-darnold', 'Sam Darnold', 3912547, 'SEA'),
  ('sam-ehlinger', 'Sam Ehlinger', 4241820, 'DEN'),
  ('sam-hartman', 'Sam Hartman', 4361994, 'WAS'),
  ('sam-howell', 'Sam Howell', 4426875, 'DAL'),
  ('sean-clifford', 'Sean Clifford', 4259592, 'CIN'),
  ('shane-buechele', 'Shane Buechele', 4039034, 'BUF'),
  ('shedeur-sanders', 'Shedeur Sanders', 4432762, 'CLE'),
  ('skylar-thompson', 'Skylar Thompson', 4036419, 'BAL'),
  ('spencer-rattler', 'Spencer Rattler', 4426339, 'NO'),
  ('stetson-bennett-iv', 'Stetson Bennett IV', 4259553, 'LAR'),
  ('tanner-mckee', 'Tanner McKee', 4685201, 'PHI'),
  ('taylen-green', 'Taylen Green', 4431325, 'CLE'),
  ('teddy-bridgewater', 'Teddy Bridgewater', 16728, 'DET'),
  ('tommy-devito', 'Tommy DeVito', 4240391, 'NE'),
  ('trevor-lawrence', 'Trevor Lawrence', 4360310, 'JAX'),
  ('trevor-siemian', 'Trevor Siemian', 2511109, 'ATL'),
  ('trey-lance', 'Trey Lance', 4383351, 'LAC'),
  ('tua-tagovailoa', 'Tua Tagovailoa', 4241479, 'ATL'),
  ('ty-simpson', 'Ty Simpson', 4685522, 'LAR'),
  ('tyler-huntley', 'Tyler Huntley', 4035671, 'BAL'),
  ('tyler-shough', 'Tyler Shough', 4360689, 'NO'),
  ('tyrod-taylor', 'Tyrod Taylor', 14163, 'GB'),
  ('tyson-bagent', 'Tyson Bagent', 4434153, 'CHI'),
  ('will-howard', 'Will Howard', 4429955, 'PIT'),
  ('will-levis', 'Will Levis', 4361418, 'TEN'),
  ('zach-wilson', 'Zach Wilson', 4361259, 'NO')
on conflict (slug) do update set full_name = excluded.full_name, espn_id = excluded.espn_id, default_team_code = excluded.default_team_code;

-- Rankmaster Was Wrong
delete from public.wrong_entries;
insert into public.wrong_entries (sort, grade, week_ref, take, what_happened, verdict) values
  (0, 'F', 'Week 4', 'Sam Darnold is what he''s always been. Do not fall for it. He will break your heart by Halloween.', 'Threw for 300+ in three of the next four, made the list at #10, and I had to write a very public apology.', 'The seeing-ghosts era ended and I was still holding the flashlight.'),
  (1, 'D', 'Week 2', 'Jayden Daniels is a fun story but rookies hit the wall. Slotting him at #9 and that''s generous.', 'Never hit the wall. Climbed to #6 and looks like a franchise cornerstone.', 'Underrated the rookie. Won''t happen again. (It will happen again.)'),
  (2, 'C', 'Week 7', 'Mahomes at #1 is the safe pick and the safe pick is the right pick. Lock it in.', 'The eye test soured for a month while Lamar ran away with it.', 'Loyalty is a hell of a drug. Diagnosis: too loyal.');

-- Weeks
insert into public.weeks (season, week_number, display_date, tagline, status, published_at, worst_name, worst_take, dropped_out, archive_note) values
  (2024, 13, 'Dec 3, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Still no arguments left to win.'),
  (2024, 12, 'Nov 26, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'One week on the throne, then gave it back.'),
  (2024, 11, 'Nov 19, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Business as usual in Baltimore.'),
  (2024, 10, 'Nov 12, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Undefeated ugly is still undefeated.'),
  (2024, 9, 'Nov 5, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'The MVP tour makes a stop.'),
  (2024, 8, 'Oct 29, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Bullied a division rival on Sunday night.'),
  (2024, 7, 'Oct 22, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Cincinnati''s one-man rescue mission.'),
  (2024, 6, 'Oct 15, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Perfect passer rating, imperfect defense.'),
  (2024, 5, 'Oct 8, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Truck-stick tour continues.'),
  (2024, 4, 'Oct 1, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Mr. Irrelevant''s brief reign.'),
  (2024, 3, 'Sep 24, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Rust, wins, and a #1 anyway.'),
  (2024, 2, 'Sep 17, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'Week 2 statement game.'),
  (2024, 1, 'Sep 10, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), null, null, '[]'::jsonb, 'The list begins where it always does.'),
  (2024, 14, 'Dec 10, 2024', 'your favorite rapper''s favorite top 10 list', 'published', now(), 'The QB Who Shall Not Be Named', 'Threw it to the other team so much they sent him a thank-you card. Three picks, one of which the defense is still laughing about.', '[{"name":"Justin Herbert","previousRank":7},{"name":"Kirk Cousins","previousRank":9},{"name":"Dak Prescott","previousRank":10}]'::jsonb, 'Bought the courthouse. Renamed it.')
on conflict (season, week_number) do update set display_date = excluded.display_date, tagline = excluded.tagline, status = excluded.status, published_at = excluded.published_at, worst_name = excluded.worst_name, worst_take = excluded.worst_take, dropped_out = excluded.dropped_out, archive_note = excluded.archive_note;

-- Rankings
delete from public.rankings;
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 13), 1, (select id from public.qbs where slug = 'lamar-jackson'), 'lamar-jackson', 'Lamar Jackson', 'BAL', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 12), 1, (select id from public.qbs where slug = 'josh-allen'), 'josh-allen', 'Josh Allen', 'BUF', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 11), 1, (select id from public.qbs where slug = 'lamar-jackson'), 'lamar-jackson', 'Lamar Jackson', 'BAL', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 10), 1, (select id from public.qbs where slug = 'patrick-mahomes'), 'patrick-mahomes', 'Patrick Mahomes', 'KC', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 9), 1, (select id from public.qbs where slug = 'lamar-jackson'), 'lamar-jackson', 'Lamar Jackson', 'BAL', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 8), 1, (select id from public.qbs where slug = 'josh-allen'), 'josh-allen', 'Josh Allen', 'BUF', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 7), 1, (select id from public.qbs where slug = 'joe-burrow'), 'joe-burrow', 'Joe Burrow', 'CIN', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 6), 1, (select id from public.qbs where slug = 'jared-goff'), 'jared-goff', 'Jared Goff', 'DET', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 5), 1, (select id from public.qbs where slug = 'josh-allen'), 'josh-allen', 'Josh Allen', 'BUF', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 4), 1, (select id from public.qbs where slug = 'brock-purdy'), 'brock-purdy', 'Brock Purdy', 'SF', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 3), 1, (select id from public.qbs where slug = 'patrick-mahomes'), 'patrick-mahomes', 'Patrick Mahomes', 'KC', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 2), 1, (select id from public.qbs where slug = 'josh-allen'), 'josh-allen', 'Josh Allen', 'BUF', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 1), 1, (select id from public.qbs where slug = 'lamar-jackson'), 'lamar-jackson', 'Lamar Jackson', 'BAL', '', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 1, (select id from public.qbs where slug = 'lamar-jackson'), 'lamar-jackson', 'Lamar Jackson', 'BAL', 'The debate is over. He didn''t just win the argument — he bought the courthouse and renamed it after himself.', '{"kind":"holds","weeks":6}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 2, (select id from public.qbs where slug = 'josh-allen'), 'josh-allen', 'Josh Allen', 'BUF', 'MVP frontrunner who plays like the game owes him money. If he''d stop trying to truck-stick linebackers on 3rd-and-2 he''d be pushing #1.', '{"kind":"up","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 3, (select id from public.qbs where slug = 'patrick-mahomes'), 'patrick-mahomes', 'Patrick Mahomes', 'KC', 'Still Mahomes. Still terrifying. But the highlight reel''s been on airplane mode and the eye test doesn''t lie. Slot three, no apologies.', '{"kind":"down","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 4, (select id from public.qbs where slug = 'brock-purdy'), 'brock-purdy', 'Brock Purdy', 'SF', 'Mr. Irrelevant is now dangerously relevant. Yes I''m biased. No I won''t apologize. The tape is immaculate and so is my conscience.', '{"kind":"up","delta":2}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 5, (select id from public.qbs where slug = 'joe-burrow'), 'joe-burrow', 'Joe Burrow', 'CIN', 'Carrying that roster like a piano up five flights of stairs. Give this man a defense and we''ll talk top two.', '{"kind":"same"}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 6, (select id from public.qbs where slug = 'jayden-daniels'), 'jayden-daniels', 'Jayden Daniels', 'WAS', 'The rookie who skipped the rookie part. Fearless, accurate, and already living rent-free in three division rivals'' nightmares.', '{"kind":"up","delta":3}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 7, (select id from public.qbs where slug = 'jared-goff'), 'jared-goff', 'Jared Goff', 'DET', 'Indoors he''s a surgeon. Outdoors he''s a coin flip. Detroit''s ceiling is real — but so is the weather in January.', '{"kind":"down","delta":2}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 8, (select id from public.qbs where slug = 'jalen-hurts'), 'jalen-hurts', 'Jalen Hurts', 'PHI', 'The Tush Push is undefeated; the deep ball is playing hard to get. Wins games, loses arguments with the film.', '{"kind":"down","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 9, (select id from public.qbs where slug = 'baker-mayfield'), 'baker-mayfield', 'Baker Mayfield', 'TB', 'The redemption arc nobody ordered and everybody''s enjoying. Chip on the shoulder, ball on a rope. Respect.', '{"kind":"up","delta":1}'::jsonb);
insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values ((select id from public.weeks where season = 2024 and week_number = 14), 10, (select id from public.qbs where slug = 'sam-darnold'), 'sam-darnold', 'Sam Darnold', 'SEA', 'I know. I KNOW. But look at the numbers before you @ me. The seeing-ghosts era is officially over. Welcome back to the list.', '{"kind":"new"}'::jsonb);

