/**
 * QB + team reference data.
 *
 * Team colors: from the current top10qb.com production bundle, with the design
 * handoff README's team-accent values winning where they differ (Bills,
 * Commanders) — that's what the mockup spines show.
 *
 * QB list: pulled from ESPN's live rosters via scripts/fetch-qbs.ts (every
 * rostered starter + backup, with correct ESPN ids for headshots). Re-run that
 * script to refresh when rosters change. `defaultTeamCode` is just the picker's
 * default — the admin can override the team per week, and each ranking snapshots
 * its own team.
 */

export type Team = {
  code: string;
  name: string;
  primaryColor: string;
};

export type QBRef = {
  slug: string;
  fullName: string;
  espnId: number;
  defaultTeamCode: string;
};

export const TEAMS: Team[] = [
  { code: "BAL", name: "Baltimore Ravens", primaryColor: "#241773" },
  { code: "KC", name: "Kansas City Chiefs", primaryColor: "#E31837" },
  { code: "BUF", name: "Buffalo Bills", primaryColor: "#C60C30" }, // design value
  { code: "CIN", name: "Cincinnati Bengals", primaryColor: "#FB4F14" },
  { code: "PHI", name: "Philadelphia Eagles", primaryColor: "#004C54" },
  { code: "HOU", name: "Houston Texans", primaryColor: "#03202F" },
  { code: "WAS", name: "Washington Commanders", primaryColor: "#5A1414" }, // design value
  { code: "SF", name: "San Francisco 49ers", primaryColor: "#AA0000" },
  { code: "DAL", name: "Dallas Cowboys", primaryColor: "#003594" },
  { code: "SEA", name: "Seattle Seahawks", primaryColor: "#002244" },
  { code: "CAR", name: "Carolina Panthers", primaryColor: "#0085CA" },
  { code: "MIA", name: "Miami Dolphins", primaryColor: "#008E97" },
  { code: "LAC", name: "Los Angeles Chargers", primaryColor: "#0080C6" },
  { code: "MIN", name: "Minnesota Vikings", primaryColor: "#4F2683" },
  { code: "GB", name: "Green Bay Packers", primaryColor: "#203731" },
  { code: "DET", name: "Detroit Lions", primaryColor: "#0076B6" },
  { code: "TB", name: "Tampa Bay Buccaneers", primaryColor: "#D50A0A" },
  { code: "ATL", name: "Atlanta Falcons", primaryColor: "#A71930" },
  { code: "NO", name: "New Orleans Saints", primaryColor: "#D3BC8D" },
  { code: "ARI", name: "Arizona Cardinals", primaryColor: "#97233F" },
  { code: "LAR", name: "Los Angeles Rams", primaryColor: "#003594" },
  { code: "CHI", name: "Chicago Bears", primaryColor: "#0B162A" },
  { code: "NYJ", name: "New York Jets", primaryColor: "#125740" },
  { code: "NYG", name: "New York Giants", primaryColor: "#0B2265" },
  { code: "PIT", name: "Pittsburgh Steelers", primaryColor: "#FFB612" },
  { code: "DEN", name: "Denver Broncos", primaryColor: "#FB4F14" },
  { code: "JAX", name: "Jacksonville Jaguars", primaryColor: "#006778" },
  { code: "TEN", name: "Tennessee Titans", primaryColor: "#4B92DB" },
  { code: "IND", name: "Indianapolis Colts", primaryColor: "#002C5F" },
  { code: "NE", name: "New England Patriots", primaryColor: "#002244" },
  { code: "CLE", name: "Cleveland Browns", primaryColor: "#311D00" },
  { code: "LV", name: "Las Vegas Raiders", primaryColor: "#A5ACAF" },
];

export const TEAM_BY_CODE: Record<string, Team> = Object.fromEntries(
  TEAMS.map((t) => [t.code, t]),
);

// Generated by scripts/fetch-qbs.ts from ESPN live rosters.
export const QBS: QBRef[] = [
  { slug: "aaron-rodgers", fullName: "Aaron Rodgers", espnId: 8439, defaultTeamCode: "PIT" },
  { slug: "adrian-martinez", fullName: "Adrian Martinez", espnId: 4361182, defaultTeamCode: "SF" },
  { slug: "aidan-oconnell", fullName: "Aidan O'Connell", espnId: 4260394, defaultTeamCode: "LV" },
  { slug: "andy-dalton", fullName: "Andy Dalton", espnId: 14012, defaultTeamCode: "PHI" },
  { slug: "anthony-richardson-sr", fullName: "Anthony Richardson Sr.", espnId: 4429084, defaultTeamCode: "IND" },
  { slug: "athan-kaliakmanis", fullName: "Athan Kaliakmanis", espnId: 4432722, defaultTeamCode: "WAS" },
  { slug: "bailey-zappe", fullName: "Bailey Zappe", espnId: 4250360, defaultTeamCode: "NYJ" },
  { slug: "baker-mayfield", fullName: "Baker Mayfield", espnId: 3052587, defaultTeamCode: "TB" },
  { slug: "behren-morton", fullName: "Behren Morton", espnId: 4431465, defaultTeamCode: "NE" },
  { slug: "bo-nix", fullName: "Bo Nix", espnId: 4426338, defaultTeamCode: "DEN" },
  { slug: "brady-cook", fullName: "Brady Cook", espnId: 4429435, defaultTeamCode: "NYJ" },
  { slug: "brandon-allen", fullName: "Brandon Allen", espnId: 2574511, defaultTeamCode: "NYG" },
  { slug: "brock-purdy", fullName: "Brock Purdy", espnId: 4361741, defaultTeamCode: "SF" },
  { slug: "bryce-young", fullName: "Bryce Young", espnId: 4685720, defaultTeamCode: "CAR" },
  { slug: "cj-stroud", fullName: "C.J. Stroud", espnId: 4432577, defaultTeamCode: "HOU" },
  { slug: "cade-klubnik", fullName: "Cade Klubnik", espnId: 4685413, defaultTeamCode: "NYJ" },
  { slug: "caleb-williams", fullName: "Caleb Williams", espnId: 4431611, defaultTeamCode: "CHI" },
  { slug: "cam-miller", fullName: "Cam Miller", espnId: 4693331, defaultTeamCode: "MIA" },
  { slug: "cam-ward", fullName: "Cam Ward", espnId: 4688380, defaultTeamCode: "TEN" },
  { slug: "carson-beck", fullName: "Carson Beck", espnId: 4430841, defaultTeamCode: "ARI" },
  { slug: "carson-wentz", fullName: "Carson Wentz", espnId: 2573079, defaultTeamCode: "MIN" },
  { slug: "carter-bradley", fullName: "Carter Bradley", espnId: 4362260, defaultTeamCode: "JAX" },
  { slug: "case-keenum", fullName: "Case Keenum", espnId: 15168, defaultTeamCode: "CHI" },
  { slug: "chris-oladokun", fullName: "Chris Oladokun", espnId: 4044111, defaultTeamCode: "KC" },
  { slug: "cole-payton", fullName: "Cole Payton", espnId: 4879250, defaultTeamCode: "PHI" },
  { slug: "connor-bazelak", fullName: "Connor Bazelak", espnId: 4426444, defaultTeamCode: "TB" },
  { slug: "dak-prescott", fullName: "Dak Prescott", espnId: 2577417, defaultTeamCode: "DAL" },
  { slug: "daniel-jones", fullName: "Daniel Jones", espnId: 3917792, defaultTeamCode: "IND" },
  { slug: "davis-mills", fullName: "Davis Mills", espnId: 4242546, defaultTeamCode: "HOU" },
  { slug: "deshaun-watson", fullName: "Deshaun Watson", espnId: 3122840, defaultTeamCode: "CLE" },
  { slug: "diego-pavia", fullName: "Diego Pavia", espnId: 5084180, defaultTeamCode: "BAL" },
  { slug: "dillon-gabriel", fullName: "Dillon Gabriel", espnId: 4427238, defaultTeamCode: "CLE" },
  { slug: "dj-uiagalelei", fullName: "DJ Uiagalelei", espnId: 4429020, defaultTeamCode: "LAC" },
  { slug: "drake-maye", fullName: "Drake Maye", espnId: 4431452, defaultTeamCode: "NE" },
  { slug: "drew-allar", fullName: "Drew Allar", espnId: 4714771, defaultTeamCode: "PIT" },
  { slug: "drew-lock", fullName: "Drew Lock", espnId: 3924327, defaultTeamCode: "SEA" },
  { slug: "easton-stick", fullName: "Easton Stick", espnId: 3120590, defaultTeamCode: "IND" },
  { slug: "fernando-mendoza", fullName: "Fernando Mendoza", espnId: 4837248, defaultTeamCode: "LV" },
  { slug: "gardner-minshew-ii", fullName: "Gardner Minshew II", espnId: 4038524, defaultTeamCode: "ARI" },
  { slug: "garrett-nussmeier", fullName: "Garrett Nussmeier", espnId: 4567747, defaultTeamCode: "KC" },
  { slug: "geno-smith", fullName: "Geno Smith", espnId: 15864, defaultTeamCode: "NYJ" },
  { slug: "graham-mertz", fullName: "Graham Mertz", espnId: 4426335, defaultTeamCode: "HOU" },
  { slug: "haynes-king", fullName: "Haynes King", espnId: 4428993, defaultTeamCode: "CAR" },
  { slug: "hendon-hooker", fullName: "Hendon Hooker", espnId: 4240858, defaultTeamCode: "TEN" },
  { slug: "hunter-dekkers", fullName: "Hunter Dekkers", espnId: 4565358, defaultTeamCode: "NO" },
  { slug: "jj-mccarthy", fullName: "J.J. McCarthy", espnId: 4433970, defaultTeamCode: "MIN" },
  { slug: "jack-strand", fullName: "Jack Strand", espnId: 5344782, defaultTeamCode: "ATL" },
  { slug: "jacob-clark", fullName: "Jacob Clark", espnId: 4569535, defaultTeamCode: "LV" },
  { slug: "jacoby-brissett", fullName: "Jacoby Brissett", espnId: 2578570, defaultTeamCode: "ARI" },
  { slug: "jake-browning", fullName: "Jake Browning", espnId: 3886812, defaultTeamCode: "TB" },
  { slug: "jalen-hurts", fullName: "Jalen Hurts", espnId: 4040715, defaultTeamCode: "PHI" },
  { slug: "jalen-milroe", fullName: "Jalen Milroe", espnId: 4432734, defaultTeamCode: "SEA" },
  { slug: "jalon-daniels", fullName: "Jalon Daniels", espnId: 4596472, defaultTeamCode: "TB" },
  { slug: "jameis-winston", fullName: "Jameis Winston", espnId: 2969939, defaultTeamCode: "NYG" },
  { slug: "jared-goff", fullName: "Jared Goff", espnId: 3046779, defaultTeamCode: "DET" },
  { slug: "jarrett-stidham", fullName: "Jarrett Stidham", espnId: 3892775, defaultTeamCode: "DEN" },
  { slug: "jaxson-dart", fullName: "Jaxson Dart", espnId: 4689114, defaultTeamCode: "NYG" },
  { slug: "jayden-daniels", fullName: "Jayden Daniels", espnId: 4426348, defaultTeamCode: "WAS" },
  { slug: "joe-burrow", fullName: "Joe Burrow", espnId: 3915511, defaultTeamCode: "CIN" },
  { slug: "joe-fagnano", fullName: "Joe Fagnano", espnId: 4429582, defaultTeamCode: "BAL" },
  { slug: "joe-flacco", fullName: "Joe Flacco", espnId: 11252, defaultTeamCode: "CIN" },
  { slug: "joe-milton-iii", fullName: "Joe Milton III", espnId: 4360698, defaultTeamCode: "DAL" },
  { slug: "joey-aguilar", fullName: "Joey Aguilar", espnId: 5151948, defaultTeamCode: "JAX" },
  { slug: "jordan-love", fullName: "Jordan Love", espnId: 4036378, defaultTeamCode: "GB" },
  { slug: "josh-allen", fullName: "Josh Allen", espnId: 3918298, defaultTeamCode: "BUF" },
  { slug: "josh-johnson", fullName: "Josh Johnson", espnId: 11394, defaultTeamCode: "CIN" },
  { slug: "justin-fields", fullName: "Justin Fields", espnId: 4362887, defaultTeamCode: "KC" },
  { slug: "justin-herbert", fullName: "Justin Herbert", espnId: 4038941, defaultTeamCode: "LAC" },
  { slug: "kedon-slovis", fullName: "Kedon Slovis", espnId: 4428512, defaultTeamCode: "ARI" },
  { slug: "kenny-pickett", fullName: "Kenny Pickett", espnId: 4240703, defaultTeamCode: "CAR" },
  { slug: "kirk-cousins", fullName: "Kirk Cousins", espnId: 14880, defaultTeamCode: "LV" },
  { slug: "kurtis-rourke", fullName: "Kurtis Rourke", espnId: 4430431, defaultTeamCode: "SF" },
  { slug: "kyle-allen", fullName: "Kyle Allen", espnId: 3115293, defaultTeamCode: "BUF" },
  { slug: "kyle-mccord", fullName: "Kyle McCord", espnId: 4433971, defaultTeamCode: "GB" },
  { slug: "kyler-murray", fullName: "Kyler Murray", espnId: 3917315, defaultTeamCode: "MIN" },
  { slug: "kyron-drones", fullName: "Kyron Drones", espnId: 4678010, defaultTeamCode: "GB" },
  { slug: "lamar-jackson", fullName: "Lamar Jackson", espnId: 3916387, defaultTeamCode: "BAL" },
  { slug: "luke-altmyer", fullName: "Luke Altmyer", espnId: 4597679, defaultTeamCode: "DET" },
  { slug: "mac-jones", fullName: "Mac Jones", espnId: 4241464, defaultTeamCode: "SF" },
  { slug: "malik-willis", fullName: "Malik Willis", espnId: 4242512, defaultTeamCode: "MIA" },
  { slug: "marcus-mariota", fullName: "Marcus Mariota", espnId: 2576980, defaultTeamCode: "WAS" },
  { slug: "mark-gronowski", fullName: "Mark Gronowski", espnId: 4695400, defaultTeamCode: "MIA" },
  { slug: "mason-rudolph", fullName: "Mason Rudolph", espnId: 3116407, defaultTeamCode: "PIT" },
  { slug: "matthew-caldwell", fullName: "Matthew Caldwell", espnId: 4877717, defaultTeamCode: "LAR" },
  { slug: "matthew-stafford", fullName: "Matthew Stafford", espnId: 12483, defaultTeamCode: "LAR" },
  { slug: "max-brosmer", fullName: "Max Brosmer", espnId: 4573398, defaultTeamCode: "MIN" },
  { slug: "michael-penix-jr", fullName: "Michael Penix Jr.", espnId: 4360423, defaultTeamCode: "ATL" },
  { slug: "miller-moss", fullName: "Miller Moss", espnId: 4431580, defaultTeamCode: "CHI" },
  { slug: "mitchell-trubisky", fullName: "Mitchell Trubisky", espnId: 3039707, defaultTeamCode: "TEN" },
  { slug: "nick-mullens", fullName: "Nick Mullens", espnId: 3059989, defaultTeamCode: "JAX" },
  { slug: "patrick-mahomes", fullName: "Patrick Mahomes", espnId: 3139477, defaultTeamCode: "KC" },
  { slug: "quinn-ewers", fullName: "Quinn Ewers", espnId: 4889929, defaultTeamCode: "MIA" },
  { slug: "riley-leonard", fullName: "Riley Leonard", espnId: 4683423, defaultTeamCode: "IND" },
  { slug: "sam-darnold", fullName: "Sam Darnold", espnId: 3912547, defaultTeamCode: "SEA" },
  { slug: "sam-ehlinger", fullName: "Sam Ehlinger", espnId: 4241820, defaultTeamCode: "DEN" },
  { slug: "sam-hartman", fullName: "Sam Hartman", espnId: 4361994, defaultTeamCode: "WAS" },
  { slug: "sam-howell", fullName: "Sam Howell", espnId: 4426875, defaultTeamCode: "DAL" },
  { slug: "sean-clifford", fullName: "Sean Clifford", espnId: 4259592, defaultTeamCode: "CIN" },
  { slug: "shane-buechele", fullName: "Shane Buechele", espnId: 4039034, defaultTeamCode: "BUF" },
  { slug: "shedeur-sanders", fullName: "Shedeur Sanders", espnId: 4432762, defaultTeamCode: "CLE" },
  { slug: "skylar-thompson", fullName: "Skylar Thompson", espnId: 4036419, defaultTeamCode: "BAL" },
  { slug: "spencer-rattler", fullName: "Spencer Rattler", espnId: 4426339, defaultTeamCode: "NO" },
  { slug: "stetson-bennett-iv", fullName: "Stetson Bennett IV", espnId: 4259553, defaultTeamCode: "LAR" },
  { slug: "tanner-mckee", fullName: "Tanner McKee", espnId: 4685201, defaultTeamCode: "PHI" },
  { slug: "taylen-green", fullName: "Taylen Green", espnId: 4431325, defaultTeamCode: "CLE" },
  { slug: "teddy-bridgewater", fullName: "Teddy Bridgewater", espnId: 16728, defaultTeamCode: "DET" },
  { slug: "tommy-devito", fullName: "Tommy DeVito", espnId: 4240391, defaultTeamCode: "NE" },
  { slug: "trevor-lawrence", fullName: "Trevor Lawrence", espnId: 4360310, defaultTeamCode: "JAX" },
  { slug: "trevor-siemian", fullName: "Trevor Siemian", espnId: 2511109, defaultTeamCode: "ATL" },
  { slug: "trey-lance", fullName: "Trey Lance", espnId: 4383351, defaultTeamCode: "LAC" },
  { slug: "tua-tagovailoa", fullName: "Tua Tagovailoa", espnId: 4241479, defaultTeamCode: "ATL" },
  { slug: "ty-simpson", fullName: "Ty Simpson", espnId: 4685522, defaultTeamCode: "LAR" },
  { slug: "tyler-huntley", fullName: "Tyler Huntley", espnId: 4035671, defaultTeamCode: "BAL" },
  { slug: "tyler-shough", fullName: "Tyler Shough", espnId: 4360689, defaultTeamCode: "NO" },
  { slug: "tyrod-taylor", fullName: "Tyrod Taylor", espnId: 14163, defaultTeamCode: "GB" },
  { slug: "tyson-bagent", fullName: "Tyson Bagent", espnId: 4434153, defaultTeamCode: "CHI" },
  { slug: "will-howard", fullName: "Will Howard", espnId: 4429955, defaultTeamCode: "PIT" },
  { slug: "will-levis", fullName: "Will Levis", espnId: 4361418, defaultTeamCode: "TEN" },
  { slug: "zach-wilson", fullName: "Zach Wilson", espnId: 4361259, defaultTeamCode: "NO" },
];

export const QB_BY_SLUG: Record<string, QBRef> = Object.fromEntries(
  QBS.map((q) => [q.slug, q]),
);

/** ESPN combiner headshot URL — transparent cutout PNG, resizable via w/h. */
export function espnHeadshot(espnId: number, w = 350, h = 254): string {
  return `https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/${espnId}.png&w=${w}&h=${h}&cb=1`;
}

/** firstName from a full name, for "View {first}'s trend →" links. */
export function firstName(fullName: string): string {
  return fullName.split(" ")[0];
}
