/**
 * Generates supabase/seed.sql from the same reference data + Week 14 sample used
 * by the app, so the database can be seeded straight from the Supabase SQL
 * editor (no service-role key needed). Run: npx tsx scripts/gen-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { QB_BY_SLUG, QBS, TEAMS } from "../lib/reference";
import { ARCHIVE, WEEK_14, WRONG_ENTRIES } from "../lib/fixtures";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const lines: string[] = [];
lines.push("-- Auto-generated by scripts/gen-seed-sql.ts — do not edit by hand.");
lines.push("-- Run AFTER schema.sql + rls.sql. Safe to re-run (idempotent).");
lines.push("");

// Teams
lines.push("-- Teams");
lines.push("insert into public.teams (code, name, primary_color) values");
lines.push(
  TEAMS.map((t) => `  (${q(t.code)}, ${q(t.name)}, ${q(t.primaryColor)})`).join(",\n") +
    "\non conflict (code) do update set name = excluded.name, primary_color = excluded.primary_color;",
);
lines.push("");

// QBs
lines.push("-- Quarterbacks");
lines.push("insert into public.qbs (slug, full_name, espn_id, default_team_code) values");
lines.push(
  QBS.map((v) => `  (${q(v.slug)}, ${q(v.fullName)}, ${v.espnId}, ${q(v.defaultTeamCode)})`).join(
    ",\n",
  ) +
    "\non conflict (slug) do update set full_name = excluded.full_name, espn_id = excluded.espn_id, default_team_code = excluded.default_team_code;",
);
lines.push("");

// Wrong entries (replace set)
lines.push("-- Rankmaster Was Wrong");
lines.push("delete from public.wrong_entries;");
lines.push("insert into public.wrong_entries (sort, grade, week_ref, take, what_happened, verdict) values");
lines.push(
  WRONG_ENTRIES.map(
    (e, i) =>
      `  (${i}, ${q(e.grade)}, ${q(e.weekRef)}, ${q(e.take)}, ${q(e.whatHappened)}, ${q(e.verdict)})`,
  ).join(",\n") + ";",
);
lines.push("");

// Weeks — prior 13 (#1 only) + Week 14 (full)
lines.push("-- Weeks");
type WeekIns = {
  season: number;
  week: number;
  date: string;
  tagline: string;
  worstName: string | null;
  worstTake: string | null;
  dropped: unknown;
  note: string;
};
const weekInserts: WeekIns[] = [];
for (const a of ARCHIVE.filter((x) => x.weekNumber < 14)) {
  weekInserts.push({
    season: a.season,
    week: a.weekNumber,
    date: a.displayDate,
    tagline: "your favorite rapper's favorite top 10 list",
    worstName: null,
    worstTake: null,
    dropped: [],
    note: a.note,
  });
}
weekInserts.push({
  season: WEEK_14.season,
  week: WEEK_14.weekNumber,
  date: WEEK_14.displayDate,
  tagline: WEEK_14.tagline,
  worstName: WEEK_14.worst?.name ?? null,
  worstTake: WEEK_14.worst?.take ?? null,
  dropped: WEEK_14.droppedOut,
  note: "Bought the courthouse. Renamed it.",
});

lines.push(
  "insert into public.weeks (season, week_number, display_date, tagline, status, published_at, worst_name, worst_take, dropped_out, archive_note) values",
);
lines.push(
  weekInserts
    .map(
      (w) =>
        `  (${w.season}, ${w.week}, ${q(w.date)}, ${q(w.tagline)}, 'published', now(), ${
          w.worstName ? q(w.worstName) : "null"
        }, ${w.worstTake ? q(w.worstTake) : "null"}, ${jsonb(w.dropped)}, ${q(w.note)})`,
    )
    .join(",\n") +
    "\non conflict (season, week_number) do update set display_date = excluded.display_date, tagline = excluded.tagline, status = excluded.status, published_at = excluded.published_at, worst_name = excluded.worst_name, worst_take = excluded.worst_take, dropped_out = excluded.dropped_out, archive_note = excluded.archive_note;",
);
lines.push("");

// Rankings — clear then insert
lines.push("-- Rankings");
lines.push("delete from public.rankings;");

type RankIns = { season: number; week: number; rank: number; slug: string; name: string; team: string; take: string; movement: unknown };
const rankInserts: RankIns[] = [];
// prior weeks: #1 only
for (const a of ARCHIVE.filter((x) => x.weekNumber < 14)) {
  const slug = Object.keys(QB_BY_SLUG).find((s) => QB_BY_SLUG[s].fullName === a.no1Name);
  if (!slug) continue;
  rankInserts.push({
    season: a.season,
    week: a.weekNumber,
    rank: 1,
    slug,
    name: a.no1Name,
    team: a.no1TeamCode,
    take: "",
    movement: { kind: "same" },
  });
}
// Week 14: full 10
for (const r of WEEK_14.ranked) {
  rankInserts.push({
    season: WEEK_14.season,
    week: WEEK_14.weekNumber,
    rank: r.rank,
    slug: r.qbSlug,
    name: r.name,
    team: r.teamCode,
    take: r.take,
    movement: r.movement,
  });
}

for (const r of rankInserts) {
  lines.push(
    `insert into public.rankings (week_id, rank, qb_id, qb_slug, name, team_code, take, movement) values (` +
      `(select id from public.weeks where season = ${r.season} and week_number = ${r.week}), ` +
      `${r.rank}, (select id from public.qbs where slug = ${q(r.slug)}), ${q(r.slug)}, ${q(r.name)}, ${q(r.team)}, ${q(r.take)}, ${jsonb(r.movement)});`,
  );
}
lines.push("");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${rankInserts.length} rankings, ${weekInserts.length} weeks).`);
